# Generated by Django 6.0.2 on 2026-02-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_herald", "0005_seosettings_custom_body_end_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="seosettings",
            name="ads_txt",
            field=models.TextField(
                blank=True,
                help_text="Content for ads.txt (Authorized Digital Sellers). Leave empty to return 404. Requires including wagtail_herald.urls in your urls.py.",
                verbose_name="ads.txt content",
            ),
        ),
        migrations.AddField(
            model_name="seosettings",
            name="security_txt",
            field=models.TextField(
                blank=True,
                help_text="Content for security.txt (RFC 9116). Required fields: Contact, Expires. Leave empty to return 404. Requires including wagtail_herald.urls in your urls.py.",
                verbose_name="security.txt content",
            ),
        ),
    ]
