# Generated by Django 6.0 on 2026-03-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_herald", "0006_seosettings_ads_txt_security_txt"),
    ]

    operations = [
        migrations.AddField(
            model_name="seosettings",
            name="indexnow_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IndexNow API key for instant search engine notification on page publish.",
                max_length=128,
                verbose_name="IndexNow API Key",
            ),
        ),
    ]
