# Generated by Django 6.0.3 on 2026-03-26 16:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

WAGTAILIMAGES_IMAGE_MODEL = getattr(
    settings, "WAGTAILIMAGES_IMAGE_MODEL", "wagtailimages.Image"
)


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_herald", "0007_remove_seosettings_title_separator"),
        migrations.swappable_dependency(WAGTAILIMAGES_IMAGE_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="seosettings",
            name="indexnow_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="IndexNow API key for instant search engine notification on page publish.",
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only alphanumeric characters and hyphens are allowed.",
                        regex="^[a-zA-Z0-9\\-]*$",
                    )
                ],
                verbose_name="IndexNow API Key",
            ),
        ),
        migrations.AlterField(
            model_name="seosettings",
            name="organization_logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Logo for Schema.org structured data. Used as 'image' when Person type is selected.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=WAGTAILIMAGES_IMAGE_MODEL,
                verbose_name="Organization logo",
            ),
        ),
        migrations.AlterField(
            model_name="seosettings",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("Organization", "Organization"),
                    ("Person", "Person"),
                    ("Corporation", "Corporation"),
                    ("LocalBusiness", "Local Business"),
                    ("OnlineStore", "Online Store"),
                    ("EducationalOrganization", "Educational Organization"),
                    ("GovernmentOrganization", "Government Organization"),
                    ("NGO", "NGO"),
                ],
                default="Organization",
                help_text="Type for Schema.org (e.g., Corporation, LocalBusiness, Person)",
                max_length=50,
                verbose_name="Organization type",
            ),
        ),
    ]
