# Generated by Django 6.0.2 on 2026-07-09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_herald", "0008_seosettings_indexnow_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seosettings",
            name="gtm_server_container_url",
            field=models.URLField(
                blank=True,
                help_text="Server-side GTM container URL. When set, GTM scripts will be loaded from this URL instead of www.googletagmanager.com. Leave empty to use default Google Tag Manager.",
                verbose_name="GTM Server Container URL",
            ),
        ),
    ]
